language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
env:
  global:
  - secure: FtRPdbkLCmXgQdOn03hunzpa4GLJMvLweLLi9qC3Su8oSCnBVcGyScde0z67tNeEuQjA1mQ52DsKaEZG8n++i8l9ZcTVSgrjmRQ6u+YH23hH74mqOPZOiJJyW7nMmJy8PSa9C3/5ZoMlTwiyXy6plDCFQn+qTpj9ohlzvY7RWX0=
  - secure: Pf/V38ggv1wg81IJYAgczTBGIteajbhugrlUCDlGVy5VomNeHMNG1+cuAL3o0VysO/3j71dfL+06DAegnwGgnZokSsyhV8wrpyJZ6/UGhCviLzLTzg053vGBu6vZzu+GIUS0z+RS3hwu4G+Q5cC/RtrQfx2AbX9rfj/T64pvItc=
